spring.application.name=Event-Hub
#                                                                   SPRING-DATA JPA
spring.datasource.url=jdbc:mysql://localhost:3306/eventhub
spring.datasource.username=root
spring.datasource.password=patelprozz
spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver

#                                                                   RAZORPAY
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
razorpay.key.id =rzp_test_TZYUP8FfjEdhpz
razorpay.key.secret= cLfRwKU1YQN1vZ1927Etz7Xe
#http://localhost:8080/index.html

#                                                                      EMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=adharshpateladharsh@gmail.com
spring.mail.password= uttq jeat nbjx jjoa
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#                                                                      JWT
jwt.secret=CHANGE_THIS_TO_A_LONG_RANDOM_SECRET
jwt.expiration=86400000
